kind: pipeline
type: docker
name: default

steps:
- name: build-release-docker-image
  image: plugins/docker
  settings:
    username: 
      from_secret: harbor-username
    password: 
      from_secret: harbor-password
    repo: harbor.winters.org.nz/library/influx-mqtt-sensors
    registry: harbor.winters.org.nz
    tags: 
      - latest
      - ${DRONE_SEMVER_SHORT}
  when:
    event:
      - tag

- name: version-release-chart
  image: harbor.winters.org.nz/hub-cache/mikefarah/yq:latest
  user: 0
  commands:
    - VERTAG=$${DRONE_SEMVER_SHORT}
    - echo "New Version $${VERTAG} for influx-mqtt-sensors"
    - yq -i ".version = \"$${VERTAG}\" | .appVersion = \"$${VERTAG}\"" "charts/influx-mqtt-sensors/Chart.yaml"
    - yq -i ".image.tag = \"$${VERTAG}\"" "charts/influx-mqtt-sensors/values.yaml"
    - cat "charts/influx-mqtt-sensors/Chart.yaml"
    - cat "charts/influx-mqtt-sensors/values.yaml"
  when:
    event:
      - tag

- name: build-release-chart
  user: 0
  image: harbor.winters.org.nz/hub-cache/library/ubuntu:20.04
  environment:
    HARBOR_PASSWORD:
      from_secret: harbor-password
    HARBOR_USERNAME:
      from_secret: harbor-username
  commands:
    - VERTAG=$${DRONE_SEMVER_SHORT}
    - env
    - apt-get update
    - apt-get install -y curl git
    - curl -fsSL -o /tmp/get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    - chmod 700 /tmp/get_helm.sh
    - /tmp/get_helm.sh
    - git config --global --add safe.directory $(pwd)
    - helm registry login --username "$${HARBOR_USERNAME}" --password "$${HARBOR_PASSWORD}" harbor.winters.org.nz/k8s-at-winters/ || exit 1
    - helm registry login --username "$${HARBOR_USERNAME}" --password "$${HARBOR_PASSWORD}" harbor.winters.org.nz/private-charts/ || exit 1
    - helm package -u charts/influx-mqtt-sensors || exit 1
    - helm push "influx-mqtt-sensors-$${VERTAG}.tgz" oci://harbor.winters.org.nz/private-charts || exit 1
  depends_on:
    - version-release-chart
  when:
    event:
      - tag

- name: release
  image: harbor.winters.org.nz/hub-cache/library/ubuntu:20.04
  commands:
    - echo "Starting Release Build"
  depends_on:
    - build-release-docker-image
    - build-release-chart
  when:
    event:
      - tag
